version: '2'
services:
  config:
    image: ${namespace}/${repository}:${tag}
    environment:
      servicePort: ${servicePort}
    ports:
      - "${servicePort}:${servicePort}"
    volumes:
      - /scratch/dockerVolumes1/log/${repository}:/log
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /scratch/dockerVolumes1/db_redis:/data
    entrypoint: ["redis-server","--appendonly", "yes"]