version: '2'
services:
  zookeeper:
    image: ${namespace}/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: ${namespace}/kafka:0.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      HOSTNAME_COMMAND: wget -t3 -T2 -qO-  http://169.254.169.254/latest/meta-data/local-ipv4bash-4.2
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: [start-kafka.sh]

