version: '2'
services:
  zookeeper:
    image: ${namespace}/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: ${namespace}/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${PLATFORM_HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /scratch/dockerVolumes1/kafka:/kafka
    entrypoint: [start-kafka.sh]

