version: '2'
services:
  zookeeper:
    image: aggregatortech/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: aggregatortech/kafka:0.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.196.21.2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: [start-kafka.sh]

